server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: P0DT0H1M



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&serverTimezone=GMT
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat
      # 指定连接池中最大的活跃连接数.
      max-active: 20
      # 指定启动连接池时，初始建立的连接数量
      initial-size: 1
      # 指定连接池等待连接返回的最大等待时间，毫秒单位.
      max-wait: 60000
      # 指定必须保持连接的最小值
      min-idle: 1
      # 指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      time-between-eviction-runs-millis: 60000
      # 指定一个空闲连接最少空闲多久后可被清除.
      min-evictable-idle-time-millis: 300000
      # 指定获取连接时连接校验的sql查询语句.
      validation-query: select 1
      # 当连接空闲时，是否执行连接测试.
      test-while-idle: true
      # 当从连接池借用连接时，是否测试该连接.
      test-on-borrow: true
      # 在连接归还到连接池时是否测试该连接.
      test-on-return: true
      # 指定是否池化statements.
      pool-prepared-statements: true
      # 指定最大的打开的prepared statements(预处理语句)数量.
      max-open-prepared-statements: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    cache: false


sftp:
  host: 47.106.33.166
  port: 22
  username: root
  passwd: lhj317..
  sitepath: /home
  sync: true

  # downloadSleep: 100 #文件下载失败下次超时重试时间
  # downloadRetry: 10 #文件下载失败重试次数
  # uploadSleep: 100 #文件上传失败下次超时重试时间
  # uploadRettry: 10  #文件上传失败重试次数



mybatis:
  # mapper 文件路径
  mapper-locations: classpath*:**/mapper/*Dao.xml
  # 实体类映射文件的地址
  type-aliases-package: com.lihuajian.entity
  # 配置文件地址
  # config-location: classpath:mybatis/mybatis-config.xml

